let defaultMusic = [
  {
    name: "Thủy Chung",
    artist: "Thương Võ x Thanh Huyy",
    img: "music-1",
    src: "music-1",
  },
  {
    name: "Tháng 12 Anh Có",
    artist: "Kidz",
    img: "music-2",
    src: "music-2",
  },
  {
    name: "Đường Chân Trời",
    artist: "Tú Na x Nguyễn Hồng Thuận",
    img: "music-3",
    src: "music-3",
  },
  {
    name: "Cành Hồng Mờ Phai",
    artist: "Tú Na",
    img: "music-4",
    src: "music-4",
  },
  {
    name: "Ải Hồng Nhan",
    artist: "Cần Vinh x Lee Ken",
    img: "music-5",
    src: "music-5",
  },
  {
    name: "Mười Năm",
    artist: "Đen",
    img: "music-6",
    src: "music-6",
  },
  {
    name: "Tháng 11 Trở Gió",
    artist: "Vmosc x Lộc nhỏ x Duyn203",
    img: "music-7",
    src: "music-7",
  },
  {
    name: "Khi Cơn Mơ Dần Phai",
    artist: "Tez ft. Myra Trần",
    img: "music-8",
    src: "music-8",
  },
  {
    name: "Đêm Trắng",
    artist: "Chu Duyên x Nguyeen",
    img: "music-9",
    src: "music-9",
  },
  {
    name: "Hoa Bằng Lăng",
    artist: "Kidz",
    img: "music-10",
    src: "music-10",
  },
  {
    name: "Hôn Lễ Của Anh",
    artist: "Tuệ Ny",
    img: "music-11",
    src: "music-11",
  },
  {
    name: "Vô Tình",
    artist: "HOAPROX x XESI",
    img: "music-12",
    src: "music-12",
  },
  {
    name: "Cuộc gọi 247",
    artist: "Kidz",
    img: "music-13",
    src: "music-13",
  },
  {
    name: "Cơn Mưa Chiều Ấy",
    artist: "Datkaa",
    img: "music-14",
    src: "music-14",
  },
  {
    name: "Chàng Không Phải Tân Lang",
    artist: "Jena x Sinkra",
    img: "music-15",
    src: "music-15",
  },
  {
    name: "Chiều Thu Họa Bóng Nàng",
    artist: "Datkaa",
    img: "music-16",
    src: "music-16",
  },
  {
    name: "Tình Sầu Thiên Thu Muôn Lối",
    artist: "Doãn Hiếu",
    img: "music-17",
    src: "music-17",
  },
  {
    name: "Duyên Trời Lấy 2",
    artist: "Chung Thanh Duy x Zeaplee",
    img: "music-18",
    src: "music-18",
  },
  {
    name: "Em Của Quá Khứ",
    artist: "Huy Nam x MewMew",
    img: "music-19",
    src: "music-19",
  },
  {
    name: "Ép Duyên",
    artist: "Long Nón lá",
    img: "music-20",
    src: "music-20",
  },
  {
    name: "Gió Vẫn Hát",
    artist: "Long Phạm x Quanvrox",
    img: "music-21",
    src: "music-21",
  },
  {
    name: "Hạ Còn Vương Nắng",
    artist: "Datkaa",
    img: "music-22",
    src: "music-22",
  },
  {
    name: "Họ Yêu Ai Mất Rồi",
    artist: "Doãn Hiếu",
    img: "music-23",
    src: "music-23",
  },
  {
    name: "Anh Thương Em Nhất Mà",
    artist: "Lã. x Log x TiB",
    img: "music-24",
    src: "music-24",
  },
  {
    name: "Dáng Em",
    artist: "Dương Edward x meChill",
    img: "music-25",
    src: "music-25",
  },
  {
    name: "Cưới Thôi",
    artist: "Masew x Masiu x B Ray x TAP",
    img: "music-26",
    src: "music-26",
  },
  {
    name: "Lạc Chốn Hồng Trần",
    artist: "Lã Phong Lâm x MewMew",
    img: "music-27",
    src: "music-27",
  },
  {
    name: "Đào Nương",
    artist: "Hoàng Vương",
    img: "music-28",
    src: "music-28",
  },
  {
    name: "Đông Phai Mờ Dáng Ai",
    artist: "Datkaa",
    img: "music-29",
    src: "music-29",
  },
  {
    name: "Phận Tàn",
    artist: "TVk x Phát Lee",
    img: "music-30",
    src: "music-30",
  },
  {
    name: "Rượu Mừng Hóa Người Dưng",
    artist: "TLong x Quanvrox",
    img: "music-31",
    src: "music-31",
  },
  {
    name: "Thê Lương",
    artist: "Phúc Chinh",
    img: "music-32",
    src: "music-32",
  },
  {
    name: "Thuyền Quyên",
    artist: "Diệu Kiên x CaoTri",
    img: "music-33",
    src: "music-33",
  },
  {
    name: "Tình Ka",
    artist: "Danhka",
    img: "music-34",
    src: "music-34",
  },
  {
    name: "Trắc trở",
    artist: "X2X x MewMew",
    img: "music-35",
    src: "music-35",
  },
  {
    name: "Tuyết Yêu Thương",
    artist: "Kiều Thơ x VUX",
    img: "music-36",
    src: "music-36",
  },
  {
    name: "Cao Ốc 20",
    artist: "B RAY x DatG",
    img: "music-37",
    src: "music-37",
  },
];

// Lấy danh sách bài hát tùy chỉnh đã lưu trong localStorage (nếu có)
let customMusic = JSON.parse(localStorage.getItem("user_custom_music")) || [];

// Hợp nhất danh sách mặc định và bài hát tùy chỉnh
let allMusic = [...defaultMusic, ...customMusic];
